services:

  kafka:
  image: confluentinc/cp-kafka
  container_name: kafka 
  environment:
    KAFKA_BROKER_ID: 1 
    KAFKA_ADVERTISED_HOST_NAME: kafka:9092
    KAFKA_ZOOKEEPER_CONNECT: zookeper:2181
    KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
    KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT