services:

  zookeeper:
    image: confluentinc/cp-zookeeper
    container_name: zookeeper
    networks:
      - network
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    
  kafka:
    image: confluentinc/cp-kafka
    container_name: kafka 
    environment:
      KAFKA_BROKER_ID: 1 
      KAFKA_ADVERTISED_HOST_NAME: kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
    networks:
      - network


  kafdrop:
    image: obsidiandynamics/kafdrop
    container_name: kafdrop
    networks:
      - network 
    depends_on:
      - kafka 
      - zookeeper
    ports:
      - 19000:9000
    environment:
      KAFKA_BROKERCONNECT: kafka:29092


  producer:
    build: ./producer
    container_name: producer
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    ports: 
      - '8000:8000'
    restart: "always"
    command: /bin/bash
    networks:
      - network
    volumes:
      - app:/publisher/producer/app
  
networks:
  network:
    external: false
    
volumes:
  app:
    driver: local 
    driver_opts:
      type: none 
      o : bind 
      device : C:\Users\zahdi\Desktop\IMT chapter\Achitecture big data\Big Data project\producer\app
      