services:

  zookeeper:
    image: confluentinc/cp-zookeeper
    container_name: zookeeper
    networks:
      - network
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    
  kafka:
    image: confluentinc/cp-kafka
    container_name: kafka 
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "9091:9091"
    environment:
      KAFKA_BROKER_ID: 1 
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
    networks:
      - network


  kafdrop:
    image: obsidiandynamics/kafdrop
    container_name: kafdrop
    networks:
      - network 
    depends_on:
      - kafka 
      - zookeeper
    ports:
      - 19000:9000
    environment:
      KAFKA_BROKERCONNECT: kafka:29092


  producer:
    build: ./producer
    container_name: producer
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    ports: 
      - '8000:8000'
    restart: "always"
    command: /bin/bash
    networks:
      - network
    volumes:
      - app:/publisher/app


  spark-master:
    build: ./sparkStreaming
    container_name: spark-master
    networks:
      - network
    ports:
      - "9080:8080"
      - "7077:7077"
      - "4040:4040"
      - "7003:7000"
    volumes:
       - ./sparkStreaming/apps:/opt/spark-apps
       - ./sparkStreaming/data:/opt/spark-data
    environment:
      - SPARK_LOCAL_IP=spark-master
      - SPARK_WORKLOAD=master


  cassandra:
    image: cassandra:latest
    container_name: cassandra
    environment:
      - CASSANDRA_SEEDS=cassandra
      - HEAP_NEWSIZE=128M
      - MAX_HEAP_SIZE=1024M
    networks:
      - network


  
networks:
  network:
    external: false
    
volumes:
  app:
    driver: local 
    driver_opts:
      type: none 
      o : bind 
      device : C:\Users\zahdi\Desktop\IMT chapter\Achitecture big data\Big Data project\producer\app
      